build:
    environment:
        php: '5.5.25'
checks:
    php:
        avoid_superglobals: true
        avoid_unnecessary_concatenation: true
        avoid_usage_of_logical_operators: true
        blank_line_after_namespace_declaration: true
        classes_in_camel_caps: true
        code_rating: true
        duplication: false
        encourage_single_quotes: true
        fix_php_opening_tag: false
        function_in_camel_caps: true
        newline_at_end_of_file: true
        no_exit: false
        no_global_keyword: true
        no_goto: true
        no_mixed_inline_html: false
        no_underscore_prefix_in_methods: true
        no_underscore_prefix_in_properties: true
        one_class_per_file: true
        optional_parameters_at_the_end: true
        parameters_in_camelcaps: true
        php5_style_constructor: true
        prefer_while_loop_over_for_loop: true
        properties_in_camelcaps: true
        psr2_class_declaration: true
        psr2_control_structure_declaration: true
        psr2_switch_declaration: true
        remove_php_closing_tag: false
        require_braces_around_control_structures: true
        security_vulnerabilities: true
        side_effects_or_types: false
        single_namespace_per_use: true
        symfony_request_injection: true
        too_many_arguments: false
        uppercase_constants: true

filter:
    paths:
        - system/mobicms/*
coding_style:
    php:
        spaces:
            general:
                linefeed_character: newline
            other:
                after_type_cast: false
        braces:
            classes_functions:
                class: undefined
                function: undefined
                closure: undefined
            if:
                opening: undefined
            for:
                opening: undefined
            while:
                opening: undefined
            do_while:
                opening: undefined
            switch:
                opening: undefined
            try:
                opening: undefined
        upper_lower_casing:
            keywords:
                general: undefined
            constants:
                true_false_null: undefined
